# Generated by Django 4.1.7 on 2023-09-25 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTankLeakTestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('bzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('czone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('d1zone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('d2zone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('ezone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('fzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('gzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='HoleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('bzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('czone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('dzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('ezone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('fzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('gzone', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
