# Generated by Django 4.1.7 on 2023-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelTankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holedb',
            name='azone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='holedb',
            name='bzone',
            field=models.CharField(max_length=10),
        ),
    ]
